name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

permissions:

  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: false
        environment: azurecloud

    - name: Set Azure subscription
      run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build and push Docker image to ACR
      run: |
        IMAGE_NAME=${{ secrets.ACR_NAME }}.azurecr.io/sample-app:${{ github.sha }}
        echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Show current directory and files
      run: |
        pwd
        ls -R

    - name: Install kubelogin
      run: |
        curl -LO https://github.com/Azure/kubelogin/releases/latest/download/kubelogin-linux-amd64.zip
        unzip kubelogin-linux-amd64.zip -d kubelogin_extracted
        sudo mv kubelogin_extracted/bin/linux_amd64/kubelogin /usr/local/bin/kubelogin
        chmod +x /usr/local/bin/kubelogin
        kubelogin --version

    - name: Get AKS credentials (AAD mode)
      run: |
        az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

    - name: Setup kubelogin with azurecli mode
      run: |
        kubelogin convert-kubeconfig -l azurecli

    - name: Update deployment image and apply manifests
      run: |
        IMAGE_NAME=${{ secrets.ACR_NAME }}.azurecr.io/sample-app:${{ github.sha }}
        sed -i "s|<IMAGE_PLACEHOLDER>|$IMAGE_NAME|g" K8s/deployment.yaml
        kubectl apply -f K8s/
